// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ResumeDbContext))]
    [Migration("20250913125823_FixingResumeFeedback")]
    partial class FixingResumeFeedback
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("backend.models.Resume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePreviewUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Resumes");
                });

            modelBuilder.Entity("backend.models.ResumeFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("OverallScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResumeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedProcessingAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId")
                        .IsUnique();

                    b.ToTable("ResumeFeedbacks");
                });

            modelBuilder.Entity("backend.models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("backend.models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("backend.models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("backend.models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.models.ResumeFeedback", b =>
                {
                    b.HasOne("backend.models.Resume", "Resume")
                        .WithOne("Feedbacks")
                        .HasForeignKey("backend.models.ResumeFeedback", "ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("backend.models.FeedbackModels+AtsFeedback", "Ats", b1 =>
                        {
                            b1.Property<int>("ResumeFeedbackId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Score")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ResumeFeedbackId");

                            b1.ToTable("ResumeFeedbacks");

                            b1.ToJson("Ats");

                            b1.WithOwner()
                                .HasForeignKey("ResumeFeedbackId");

                            b1.OwnsMany("backend.models.FeedbackModels+FeedbackTip", "Tips", b2 =>
                                {
                                    b2.Property<int>("AtsFeedbackResumeFeedbackId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Explanation")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Tip")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("AtsFeedbackResumeFeedbackId", "__synthesizedOrdinal");

                                    b2.ToTable("ResumeFeedbacks");

                                    b2.WithOwner()
                                        .HasForeignKey("AtsFeedbackResumeFeedbackId");
                                });

                            b1.Navigation("Tips");
                        });

                    b.OwnsOne("backend.models.FeedbackModels+SkillsCoverageFeedback", "SkillsCoverage", b1 =>
                        {
                            b1.Property<int>("ResumeFeedbackId")
                                .HasColumnType("INTEGER");

                            b1.PrimitiveCollection<string>("DetectedSkills")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.PrimitiveCollection<string>("MissingCommonSkills")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Score")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ResumeFeedbackId");

                            b1.ToTable("ResumeFeedbacks");

                            b1.ToJson("SkillsCoverage");

                            b1.WithOwner()
                                .HasForeignKey("ResumeFeedbackId");

                            b1.OwnsMany("backend.models.FeedbackModels+FeedbackTip", "Tips", b2 =>
                                {
                                    b2.Property<int>("SkillsCoverageFeedbackResumeFeedbackId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Explanation")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Tip")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("SkillsCoverageFeedbackResumeFeedbackId", "__synthesizedOrdinal");

                                    b2.ToTable("ResumeFeedbacks");

                                    b2.WithOwner()
                                        .HasForeignKey("SkillsCoverageFeedbackResumeFeedbackId");
                                });

                            b1.Navigation("Tips");
                        });

                    b.OwnsOne("backend.models.FeedbackModels+ContentFeedback", "ContentQuality", b1 =>
                        {
                            b1.Property<int>("ResumeFeedbackId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Score")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ResumeFeedbackId");

                            b1.ToTable("ResumeFeedbacks");

                            b1.ToJson("ContentQuality");

                            b1.WithOwner()
                                .HasForeignKey("ResumeFeedbackId");

                            b1.OwnsMany("backend.models.FeedbackModels+FeedbackTip", "Tips", b2 =>
                                {
                                    b2.Property<int>("ContentFeedbackResumeFeedbackId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Explanation")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Tip")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("ContentFeedbackResumeFeedbackId", "__synthesizedOrdinal");

                                    b2.ToTable("ResumeFeedbacks");

                                    b2.WithOwner()
                                        .HasForeignKey("ContentFeedbackResumeFeedbackId");
                                });

                            b1.Navigation("Tips");
                        });

                    b.OwnsOne("backend.models.FeedbackModels+ContentFeedback", "Formatting", b1 =>
                        {
                            b1.Property<int>("ResumeFeedbackId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Score")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ResumeFeedbackId");

                            b1.ToTable("ResumeFeedbacks");

                            b1.ToJson("Formatting");

                            b1.WithOwner()
                                .HasForeignKey("ResumeFeedbackId");

                            b1.OwnsMany("backend.models.FeedbackModels+FeedbackTip", "Tips", b2 =>
                                {
                                    b2.Property<int>("ContentFeedbackResumeFeedbackId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Explanation")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Tip")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("ContentFeedbackResumeFeedbackId", "__synthesizedOrdinal");

                                    b2.ToTable("ResumeFeedbacks");

                                    b2.WithOwner()
                                        .HasForeignKey("ContentFeedbackResumeFeedbackId");
                                });

                            b1.Navigation("Tips");
                        });

                    b.OwnsOne("backend.models.FeedbackModels+ContentFeedback", "Structure", b1 =>
                        {
                            b1.Property<int>("ResumeFeedbackId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Score")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ResumeFeedbackId");

                            b1.ToTable("ResumeFeedbacks");

                            b1.ToJson("Structure");

                            b1.WithOwner()
                                .HasForeignKey("ResumeFeedbackId");

                            b1.OwnsMany("backend.models.FeedbackModels+FeedbackTip", "Tips", b2 =>
                                {
                                    b2.Property<int>("ContentFeedbackResumeFeedbackId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Explanation")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Tip")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("ContentFeedbackResumeFeedbackId", "__synthesizedOrdinal");

                                    b2.ToTable("ResumeFeedbacks");

                                    b2.WithOwner()
                                        .HasForeignKey("ContentFeedbackResumeFeedbackId");
                                });

                            b1.Navigation("Tips");
                        });

                    b.Navigation("Ats")
                        .IsRequired();

                    b.Navigation("ContentQuality")
                        .IsRequired();

                    b.Navigation("Formatting")
                        .IsRequired();

                    b.Navigation("Resume");

                    b.Navigation("SkillsCoverage")
                        .IsRequired();

                    b.Navigation("Structure")
                        .IsRequired();
                });

            modelBuilder.Entity("backend.models.Resume", b =>
                {
                    b.Navigation("Feedbacks");
                });
#pragma warning restore 612, 618
        }
    }
}
